apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_FILE
              value: /metabase-data/metabase.db
          volumeMounts:
            - name: metabase-storage
              mountPath: /metabase-data
      volumes:
        - name: metabase-storage
          persistentVolumeClaim:
            claimName: metabase-pvc
