apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: metabase
spec:
  type: NodePort
  selector:
    app: metabase
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30009
